-- CreateTable
CREATE TABLE `Portfolio` (
    `uid` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(86) NULL,
    `page_title` VARCHAR(80) NULL,
    `rental_name` VARCHAR(55) NULL,
    `address` VARCHAR(35) NULL,
    `city` VARCHAR(23) NULL,
    `postal_code` VARCHAR(6) NULL,
    `region` VARCHAR(20) NULL,
    `lead` VARCHAR(114) NULL,
    `description` VARCHAR(1773) NULL,
    `display_on_map` SMALLINT NULL,
    `display` SMALLINT NOT NULL DEFAULT 0,
    `display_priority` SMALLINT NOT NULL DEFAULT 1,
    `in_progress` SMALLINT NULL,
    `map_latitude` DECIMAL(8, 6) NULL,
    `map_longitude` DECIMAL(8, 6) NULL,
    `real_latitude` DECIMAL(8, 6) NULL,
    `real_longitude` DECIMAL(8, 6) NULL,
    `category` VARCHAR(21) NULL,
    `download_link` VARCHAR(96) NULL,
    `link` VARCHAR(79) NULL,
    `soundcloud_embed` VARCHAR(292) NULL,
    `device_primary` VARCHAR(13) NULL,
    `device_secondary` VARCHAR(12) NULL,
    `device_tertiary` VARCHAR(10) NULL,
    `languages` VARCHAR(39) NULL,
    `children` SMALLINT NULL,
    `audiodescription` SMALLINT NULL,
    `sign_language` SMALLINT NULL,
    `numeric` SMALLINT NULL,
    `rf` SMALLINT NULL,
    `ir` SMALLINT NULL,
    `rfid` SMALLINT NULL,
    `gps` SMALLINT NULL,
    `sync` SMALLINT NULL,

    PRIMARY KEY (`uid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
